### PR TITLE
Accept instances hashes on apache and http_check integrations

### PR DESCRIPTION
**Pull request by asenci**
### What does this PR do?

This allows more options to be passed directly to the configuration template, without needing to update the module every time a new option is implemented while keeping it backwards compatible with the current style of parameters.

This also removes one test case from http_check: `with headers parameter array` (I couldn't find a use case for this on the Datadog integration documentation or code).

### Motivation

Using the current method of passing options as parameters to the Puppet module requires a module update every time a new option is added to the Datadog agent integration.

### Describe your test plan

Test cases included on the respective spec files

### CODE REVIEW

**Comment by albertvaka** [comment]
Looking at the tests, there's something in this PR that Puppet 4.6 doesn't like.

File: manifests/integrations/http_check.pp [hunk 1]
```diff
@@ -227,12 +229,47 @@
...
+          Tuple(['name', $value])
+        }
+
+        'data', 'headers': {
+          $_value = datadog_agent::clean_empty($value)
+          if !$_value.is_a(Array) {
+            Tuple([$key, $_value]).next
+          }
+
+          $value_array = $_value.filter |$item| { $item =~ /:/ }
```
Comment (albertvaka) [inline manifests/integrations/http_check.pp:251]: Unused `$value_array`

File: manifests/integrations/http_check.pp [hunk 2]
```diff
@@ -227,12 +229,47 @@
...
+    Hash($instance.map |$key, $value| {
+      case $key {
+        'sitename': {
+          Tuple(['name', $value])
+        }
+
+        'data', 'headers': {
+          $_value = datadog_agent::clean_empty($value)
+          if !$_value.is_a(Array) {
+            Tuple([$key, $_value]).next
```
Comment (albertvaka) [inline manifests/integrations/http_check.pp:248]: Is this `next` a typo or does it do something?

File: manifests/integrations/http_check.pp [hunk 3]
```diff
@@ -227,12 +229,47 @@
...
+
+          Tuple([$key, datadog_agent::clean_empty($value_hash)])
+        }
+
+        'tags': {
+          Tuple([$key, datadog_agent::clean_empty($value)])
+        }
+
+        default: {
+          Tuple([$key, $value]) }
```
Comment (albertvaka) [inline manifests/integrations/http_check.pp:268]:
```suggestion
        default: {
          Tuple([$key, $value])
        }
```

**Review by albertvaka — COMMENTED** [review]
I spent a bit of time trying to debug the crash on Puppet 4.6 and I managed to track it down to this change which was added in Puppet 4.9.4: https://github.com/puppetlabs/puppet/commit/6bc88d11d75431a30defb8cde25b101c56c61a2b

Without this change, it fails with `undefined method `instance?' for nil:NilClass` but I'm not sure why. Maybe it's a good excuse to drop support for Puppet 4.6? :)

**Comment by albertvaka** [comment]
@asenci I see some activity in your branch :) Do you think you could fix the failing tests on puppet 4.6? Then we could merge this to `main`.

**Comment by asenci** [comment]
> @asenci I see some activity in your branch :) Do you think you could fix the failing tests on puppet 4.6? Then we could merge this to `main`.

Sorry for the lack of feedback, we were down a team member for a while and I didn't have much time to work on this.
I'll try to get this sorted by next week. 👍

**Comment by asenci** [comment]
Hi @albertvaka, I tried everything I could think of, but I couldn't make it work with Puppet 4.6.

It seems to be some weird interaction with the test cases when spec_helper tries to check the resulting file. It passes the tests if you disable some specific checks on `datadog_agent_integrations_http_check_spec.rb` (mostly related to empty tag testing), but I wasn't able to progress any further with the troubleshooting.

Not sure if there is anything else you would like to try, or if you'd prefer to close the PR?

**Comment by albertvaka** [comment]
A thousand thanks for all the tests you made, I could see the commits on my Github notifications 🙇 🙇 🙇

I think this change is good and important, so if that's fine for you, let's keep the PR open until either we drop support for 4.6 or someone can help solve the problem on that version.
